
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345677
      MYSQL_DATABASE: delivery_app
    volumes:
      - mysql_data:/var/lib/mysql

  keycloak:
    container_name: Keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - keycloak-network
    command:
      - "start-dev"

networks:
    keycloak-network:
      driver: bridge

volumes:
  mysql_data:

  keycloak:
    driver: local